CXXFLAGS=-g -Wall --pedantic -std=c++23

esercizio_5.3: esercizio5.3.cpp posizione.h PuntoMateriale.h CampoVettoriale.h particella.h
	g++ -o esercizio5.3 esercizio5.3.cpp ${CXXFLAGS}

clean:
	rm -f *.o