CXXFLAGS=-g -Wall --pedantic -std=c++23

esame: appello7.cpp VectorOperations.h FunzioneVettoriale.h gplot++.h funzionebase.h fmtlib.h RandomGen.h solutore.h integral.h
	g++ -o esame appello7.cpp ${CXXFLAGS}

clean:
	rm -f *.o