CXXFLAGS=-g -Wall --pedantic -std=c++23

esame: appello2.cpp VectorOperations.h FunzioneVettoriale.h gplot++.h funzionebase.h fmtlib.h RandomGen.h Esperimento.h
	g++ -o esame appello2.cpp  ${CXXFLAGS}

clean:
	rm -f *.o