CXXFLAGS=-g -Wall --pedantic -std=c++23

esame: appello8.cpp VectorOperations.h gplot++.h funzionebase.h fmtlib.h RandomGen.h solutore.h integral.h Esperimento.h FunzioneVettoriale.h 
	g++ -o esame appello8.cpp ${CXXFLAGS}

clean:
	rm -f *.o