CXXFLAGS=-g -Wall --pedantic -std=c++23

esercizio10.1: esercizio10.1.cpp RandomGen.h gplot++.h IntegralMC.h funzionebase.h
	g++ -o esercizio10.1 esercizio10.1.cpp  ${CXXFLAGS}


clean:
	rm -f *.o
	rm esercizio10.2
	rm esercizio10.2bis

all:
	esercizio10.2 \
	esercizio10.2bis