CXXFLAGS=-g -Wall --pedantic -std=c++23

esercizio10.0: esercizio10.0.cpp RandomGen.h gplot++.h IntegralMC.h funzionebase.h
	g++ -o esercizio10.0 esercizio10.0.cpp  ${CXXFLAGS}

all:
	esercizio10.2 \
	esercizio10.2bis